# RECUPERATION & PREPARATION DES FICHIERS

In [4]:
import pandas as pd
import numpy as np

# 1. Les fichiers Numpy et Dataframe

## 1.1. Génération automatique de data

### 1.1.1. Génération de data automatiquement en une liste avec les fonctions prédifinies

In [6]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np.arange(3, 15)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
np.array(range(-10, 11))

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

In [105]:
np.linspace(5, 45, 8)     # Sont indiqués ds la parenthèse début, fin, quantité

array([ 5.        , 10.71428571, 16.42857143, 22.14285714, 27.85714286,
       33.57142857, 39.28571429, 45.        ])

### # Transformation des listes en tableau

In [27]:
vector = np.arange(9)
vector                             # A vérifier ou compléter avec cours tuto vecteurs

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
matrix = np.arange(9).reshape((3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 1.1.2. Autres fonctions bultin de génération de données en liste ou en tableau

In [69]:
np.zeros(3,)

array([0., 0., 0.])

In [70]:
np.zeros((5, 3))          # Dans la parenthèse sont indiquées les valeurs du shape : nb ligns, nb colonnes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [80]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [85]:
np.eye(5)                # Dans la parenthèse, dimension de la matrice 5 indiquant nb lignes = nb de colonnes

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [102]:
np.full((4, 3), 6)       # (,) -> shape, et le dernier chiffre -> valeur dans la matrice

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

### 1.1.3. Génération aléatoire de data en liste ou en tableau avec les fonctions builtin

In [2]:
from numpy import random  # => en son absence, précéder obligatoirement les fonctions random de <np.> 
                          # => si importé, np. facultatif

In [15]:
random.random(3)

array([0.04627996, 0.67210732, 0.28389393])

In [16]:
np.random.random((5, 3))

array([[0.1868291 , 0.98125817, 0.35464818],
       [0.68217837, 0.8024909 , 0.18764442],
       [0.43169623, 0.97603671, 0.43183584],
       [0.71240751, 0.99067873, 0.45193184],
       [0.38150834, 0.03816799, 0.05527446]])

In [19]:
random.rand(5)

array([0.83045748, 0.16342892, 0.84268668, 0.57117441, 0.1936345 ])

In [17]:
random.rand(3, 4)

array([[0.82311749, 0.22554578, 0.73895531, 0.28565707],
       [0.79728924, 0.5796829 , 0.48967239, 0.81952469],
       [0.55126068, 0.84157006, 0.71031273, 0.6545457 ]])

In [21]:
random.randn(5)

array([-1.08836652,  0.9155796 ,  0.03672015, -2.34285416,  0.15974448])

In [98]:
random.randn(3, 4)

array([[-1.23333578,  1.23754475, -0.3470688 , -1.01230974],
       [-1.17238817,  0.48921967, -0.41072726, -1.8669434 ],
       [-0.2548343 , -0.62605161,  2.2587101 ,  1.35344512]])

In [71]:
random.randint(3)       # => Générer 1 nb aléatoire entre 0 et 3

1

In [62]:
random.randint(2, 6)    # => Générer 1 nb aléatoire entre 2 et 6 ?      

4

In [9]:
random.randint(low=0, high=5 , size=15)  # => 15 nb aléatoires compris entre 0 et 5

array([3, 2, 1, 4, 4, 3, 3, 0, 1, 2, 2, 4, 4, 0, 4])

In [41]:
x = random.randint(100, size=(5, 3))    # np.random.seed(1) => permet de figer les données aléatoires générées
x                                          # 100 => 15 nb (5x3) aléatoires de val maximum 100 chacun
                                           # size => shape[0] = 5 lignes et shape[1] = 3 colonnes

array([[40, 17, 83],
       [48, 56, 53],
       [ 1, 31, 59],
       [26, 69, 80],
       [35, 59, 25]])

In [25]:
for i in range(11):
    print(random.randint(5, 10))    # => affiche 11 nb entiers aléatoires compris entre 5 et 10
                                   
# Avec random.uniform(5, 10) => affiche 11 nb entiers décimaux (float) compris entre 5 et 10

8
7
9
8
6
9
6
5
6
8
6


## 1.2. Création d'un numpy ndarray

In [2]:
np.array([
         [1, 3, 5],
         [2, 4, 6]
        ])

array([[1, 3, 5],
       [2, 4, 6]])

In [3]:
data = np.array([
         [1, 3, 5],
         [2, 4, 6]])

### Création d'un vecteur

## 1.3. Création d'un objet Series Pandas
> **s = pd.Series(data = data, index = index)**

### 1.3.1. Créer une Series à partir d'une liste (ou d'un vecteur ?)

In [135]:
# 1 / Génération de données
np.arange(3, 8)

array([3, 4, 5, 6, 7])

In [136]:
# 2 / Création de l'objet Series
    # Sans spécification d'index => 1 liste

pd.Series([3, 4, 5, 6, 7])  # par défaut, l'index est implémenté sous forme de suite numérique

# pd.Series(np.arange(3, 8))

0    3
1    4
2    5
3    6
4    7
dtype: int64

In [78]:
pd.Series(np.arange(3, 8))

0    3
1    4
2    5
3    6
4    7
dtype: int64

In [79]:
    # Spécification de l'index => 2 listes
data = [3, 4, 5, 6, 7]
index = ['a', 'b', 'c', 'd', 'e']

pd.Series(data = [3, 4, 5, 6, 7], index = ['a', 'b', 'c', 'd', 'e'])

a    3
b    4
c    5
d    6
e    7
dtype: int64

In [80]:
pd.Series(data = [3, 4, 5, 6, 7], index = [np.arange(10, 15)])

10    3
11    4
12    5
13    6
14    7
dtype: int64

In [81]:
# 3 / Exemple

In [82]:
# définition de la donnée associée (températures de la semaine)
data1 = [33, 19, 15, 89, 11, -5, 9]

In [83]:
# définition de l'index associé
index1 = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'] 

In [84]:
# Création de l'objet Series s1 = pd.Series(data = data1, index = index1)
s1 = pd.Series(data = data1, index = index1)
s1

Lundi       33
Mardi       19
Mercredi    15
Jeudi       89
Vendredi    11
Samedi      -5
Dimanche     9
dtype: int64

In [150]:
    # Création de l'objet Series s1 = pd.Series(data = data1, index = index1) détaillé
s1 = pd.Series(data = [33, 19, 15, 89, 11, -5, 9], 
              index = ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'])
s1

Lundi       33
Mardi       19
Mercredi    15
Jeudi       89
Vendredi    11
Samedi      -5
Dimanche     9
dtype: int64

In [156]:
# Donner un nom à l'objet Series et à l'index

s1.name = 'Températures journalières'

s1.index.name = 'Jours de la semaine'
s1

# La disposition du nom de l'index n'est pas satisfaisante sur un objet Serises 

Jours de la semaine
Lundi       33
Mardi       19
Mercredi    15
Jeudi       89
Vendredi    11
Samedi      -5
Dimanche     9
Name: Températures journalières, dtype: int64

### 1.3.2. Créer une Series à partir d'un Dictionnaire

In [159]:
# Exemple 1

    # Données de température suivant les jours

dico = {'Lundi': 33, 'Mardi': 19, 'Mercredi': 15, 'Jeudi': 89, 'Vendredi': 11, 'Samedi': -5, 'Dimanche': 9} 

In [160]:
    # Création de l'objet Series s2

s2 = pd.Series({'Lundi': 33, 'Mardi': 19, 'Mercredi': 15, 'Jeudi': 89, 'Vendredi': 11, 'Samedi': -5, 'Dimanche':9})
s2

Lundi       33
Mardi       19
Mercredi    15
Jeudi       89
Vendredi    11
Samedi      -5
Dimanche     9
dtype: int64

In [161]:
s2 = pd.Series(dico)
s2

Lundi       33
Mardi       19
Mercredi    15
Jeudi       89
Vendredi    11
Samedi      -5
Dimanche     9
dtype: int64

In [162]:
# Exemple 2

population_dict = {'California': 38332521,'Texas': 26448193, 'New York': 19651127, 'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [163]:
# Exemple 3
area_dict = {'California': 423967, 
             'Texas': 695662,
             'New York': 141297, 
             'Florida': 170312,
             'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [164]:
print(population['California':'Florida']) # Que pensez vous de cette ligne?

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64


## 1.4. Création d'un dataframe
**df = pd.DataFrame(data = data, columns = colonnes, index = index)**
> - Un dataframe peut être considéré comme un tableau numpy nommé (au niveau des en tête de colonne) et indexé
> - Le data doit être obligatoirement un dictionnaire => clé/valeur
> - L'index est facultatif

### 1.4.1. Création d'un  Dataframe à partir d'un dictionnaire de listes

### # Exemple 1

In [20]:
# 1 / Création des listes

liste_noms = ['paul', 'radji', 'bob', 'alice']
liste_ages = [41, 53, 56, 38]
liste_poids = [12, 15.56, 98.25, 14.26]

In [85]:
# 2 / Création dictionnaire des listes

data = {
        "noms": ['paul', 'radji', 'bob', 'alice'],   # => la colonne ds le DF comportant la liste des noms        
        "ages": [41, 53, 56, 38],                      # sera intitulée "noms" et suivt
        "poids": [12, 15.56, 98.25, 14.26]
       }

In [23]:
data = {"noms": ['paul', 'radji', 'bob', 'alice'], "ages": [41, 53, 56, 38], "poids": [12, 15.56, 98.25, 14.26]}

In [22]:
data = {"noms": liste_noms, "ages": liste_ages, "poids": liste_poids}

In [24]:
data

{'noms': ['paul', 'radji', 'bob', 'alice'],
 'ages': [41, 53, 56, 38],
 'poids': [12, 15.56, 98.25, 14.26]}

In [25]:
# 3 / Création du Dataframe

data_df = pd.DataFrame(data)
data_df

noms  ages  poids
0   paul    41  12.00
1  radji    53  15.56
2    bob    56  98.25
3  alice    38  14.26

In [27]:
data_df.describe()

ages      poids
count   4.000000   4.000000
mean   47.000000  35.017500
std     8.831761  42.180653
min    38.000000  12.000000
25%    40.250000  13.695000
50%    47.000000  14.910000
75%    53.750000  36.232500
max    56.000000  98.250000

In [29]:
data_df.sum(axis=0)

noms     paulradjibobalice
ages                   188
poids               140.07
dtype: object

### # Exemple 3 : A partir d'un tableau Numpy de dimension 2
> => DataFrame à 2 colonnes

In [180]:
np.random.rand(3, 2)

array([[0.4805674 , 0.83153656],
       [0.71691052, 0.63728879],
       [0.35332938, 0.33347672]])

In [182]:
# Nommer les colonnes &  Déterminer les index avec (...., columns = [''], index = [.., ..])
  
df = pd.DataFrame(np.random.rand(3, 2), columns=['foo', 'bar'], index=['a', 'b', 'c'])
df

foo       bar
a  0.506222  0.656747
b  0.604699  0.737995
c  0.622051  0.663797

### 1.4.2. Création d'un Dataframe à partir d'une liste de dictionnaires

In [44]:
# 1 / Création de la liste de dictionnaires (correspond à un fichier json)

data = [
        {
            "nom": "paul",
            "age": 41,
          "poids": 12        
        },
        
        {
            "nom": "radji",
            "age": 53,
          "poids": 15.56     
        },
    
        {
            "nom": "mamadou",
            "age": 9,
          "poids": 20.30     
        }
]

In [87]:
    # Autre notation du fichier json

data = [{"nom": "paul", "age": 41, "poids": 12}, {"nom": "radji", "age": 53, "poids": 15.56}, 
        {"nom": "mamadou","age": 9,"poids": 20.30}]
data

[{'nom': 'paul', 'age': 41, 'poids': 12},
 {'nom': 'radji', 'age': 53, 'poids': 15.56},
 {'nom': 'mamadou', 'age': 9, 'poids': 20.3}]

In [47]:
# 2 / Création du Dataframe

data_df = pd.DataFrame(data)
data_df

nom  age  poids
0     paul   41  12.00
1    radji   53  15.56
2  mamadou    9  20.30

### # Exemple 1 : à partir d'objet Serises

In [168]:
# A partir d'un objet Series => DataFrame à une colonne

population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [170]:
df = pd.DataFrame(population)
df

0
California  38332521
Texas       26448193
New York    19651127
Florida     19552860
Illinois    12882135

In [171]:
    # Nommer la colonne avec columns = ['']

df = pd.DataFrame(population, columns=['population'])
df

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [189]:
# A partir de plusieurs Series => Dataframe à plusieurs colonnes
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [190]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [191]:
df = pd.DataFrame({'population': population, 'area': area})
df

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

### 1.4.3. Génération de dataframe par dictionnaire de liste & liste de dictionnaire avec une fonction

In [187]:
# A partir d'une liste de dict
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [188]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
df = pd.DataFrame(data)
df

a  b
0  0  0
1  1  2
2  2  4

In [88]:
# Une fonction pour générer facilement des DataFrame. 
def make_df(cols, ind):
    """Crée rapidement des DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

# exemple
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

# 2. Méthodes d'importations des différents types de fichiers

## Par Webscraping

In [45]:
# Voir chapitre dédié !!

# 3. Mise en forme du fichier

## 3.1. Concatener des dataframes

### NB : Récuperer concatenation des tableaux dans fichier modification

In [5]:
# Soit les notes des élèves de 2 classes df1 et df2. 
    # A chaque Id d'élève, correspond sa note

df1 =  pd.DataFrame({ 'StudentID': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
                     'Score' : [89, 39, 50, 97, 22, 66, 31, 51, 71, 91, 56, 32, 52, 73, 92]})
df2 =  pd.DataFrame({'StudentID': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
                     'Score': [98, 93, 44, 77, 69, 56, 31, 53, 78, 93, 56, 77, 33, 56, 27]})

In [6]:
df1.head()

StudentID  Score
0          1     89
1          3     39
2          5     50
3          7     97
4          9     22

In [7]:
df2.head()

StudentID  Score
0          2     98
1          4     93
2          6     44
3          8     77
4         10     69

In [8]:
# Concatenation des 2 datasets

pd.concat([df1,df2]) # Ajoute df2 à la suite de df1 sans réinitialiser l'index
                        # => ajouter < ignore_index=True > pour résoudre ce problème !!

StudentID  Score
0           1     89
1           3     39
2           5     50
3           7     97
4           9     22
5          11     66
6          13     31
7          15     51
8          17     71
9          19     91
10         21     56
11         23     32
12         25     52
13         27     73
14         29     92
0           2     98
1           4     93
2           6     44
3           8     77
4          10     69
5          12     56
6          14     31
7          16     53
8          18     78
9          20     93
10         22     56
11         24     77
12         26     33
13         28     56
14         30     27

In [9]:
pd.concat([df1, df2], ignore_index=True)

StudentID  Score
0           1     89
1           3     39
2           5     50
3           7     97
4           9     22
5          11     66
6          13     31
7          15     51
8          17     71
9          19     91
10         21     56
11         23     32
12         25     52
13         27     73
14         29     92
15          2     98
16          4     93
17          6     44
18          8     77
19         10     69
20         12     56
21         14     31
22         16     53
23         18     78
24         20     93
25         22     56
26         24     77
27         26     33
28         28     56
29         30     27

In [10]:
# Calcul de la moyenne générale des notes
df_moy = pd.concat([df1, df2], ignore_index=True)

In [11]:
df_moy['Score'].mean() # => En moyenne les étudiants ont 67.76 sur 100 

61.766666666666666

### Resumé :
> - Les 2 dataframes doivent avoir :
>   - le même nombre de colonnes (shape[1] égaux => cdt° assemblage vertical) !!
>   - les mêmes noms de colonnes
> - Par défaut, avec concat, axis = 0 => combinaison verticale des deux tableaux
> - Pour combiner horizontalement les deux tableaux => ... axis = 1 (Voir ci-dessous)

In [19]:
pd.concat([df1, df2], axis = 1)

StudentID  Score  StudentID  Score
0           1     89          2     98
1           3     39          4     93
2           5     50          6     44
3           7     97          8     77
4           9     22         10     69
5          11     66         12     56
6          13     31         14     31
7          15     51         16     53
8          17     71         18     78
9          19     91         20     93
10         21     56         22     56
11         23     32         24     77
12         25     52         26     33
13         27     73         28     56
14         29     92         30     27

## 3.2. Merger (Joindre) des dataframes

### 3.2.1. Merging sur des df ayant des clés identiques

In [25]:
# Classe df1 et df2 d'élèves ayant une note en Math ou en ML (Machine Learning)

df1 =  pd.DataFrame({ 'StudentID': [1, 2, 3],        # df1 => groupe des étudiants en Math
                       'ScoreMath' : [22, 66, 31]})

df2 =  pd.DataFrame({ 'StudentID': [21, 8, 3],       # df2 => groupe des étudiants en ML
                       'ScoreML' : [11, 85, 46]})

In [26]:
df1   

StudentID  ScoreMath
0          1         22
1          2         66
2          3         31

In [27]:
df2

StudentID  ScoreML
0         21       11
1          8       85
2          3       46

### 1 / Tous les étdts (unique) de df1 et df2 ayant une note ou pas en Math ou en ML

In [30]:
df1.merge(df2, how='outer')  # => NaN sera affecté aux étdts sans note en Math ou en Ml
                                # "outer" => tous les éléments uniques

StudentID  ScoreMath  ScoreML
0          1       22.0      NaN
1          2       66.0      NaN
2          3       31.0     46.0
3         21        NaN     11.0
4          8        NaN     85.0

### 2 / Tous les étudiants (unique) de df1 et df2 ayant une note en Math et ML

In [31]:
df1.merge(df2, how = "inner")    # "inner" => Tous les éléments communs aux 2 groupes

StudentID  ScoreMath  ScoreML
0          3         31       46

### 3 / Tous les étdts de df1 et ceux ayant en plus une note en ML 

In [32]:
df1.merge(df2, how="left")    # On considère les étudiants de df1 (Math) et en :  
                                # récupérant leur notes en ML si elles existent
                                # leur affectant NaN s'ils n'ont pas de notes

StudentID  ScoreMath  ScoreML
0          1         22      NaN
1          2         66      NaN
2          3         31     46.0

### 4 / Tous les étdts de df2 et ceux ayant en plus une note en Maths

In [33]:
df1.merge(df2, how='right')   # On considère les étudiants de df2 (ML) et en :  
                                # récupérant leur notes en Math si elles existent
                                # leur affectant NaN s'ils n'ont pas de notes

StudentID  ScoreMath  ScoreML
0         21        NaN       11
1          8        NaN       85
2          3       31.0       46

### 5 / Syntaxes équivalentes en dataframe

In [34]:
pd.merge(df1, df2, how="inner")

StudentID  ScoreMath  ScoreML
0          3         31       46

In [35]:
pd.merge(df1, df2, how="right")

StudentID  ScoreMath  ScoreML
0         21        NaN       11
1          8        NaN       85
2          3       31.0       46

## 3.2.2. Merging sur l'index

Lorsqu'il n'y a pas de nom de colonne commun aux 2 dataframes, on utilise cette méthode pour préciser nous même les noms de colonne pour la jointure

In [37]:
left1 = pd.DataFrame({'key': ['apple','ball','apple', 'apple',
'ball', 'cat'], 'value': range(6)})

right1 = pd.DataFrame({'group_val': [33.4, 5]}, index=['apple',
'ball'])

In [38]:
left1

key  value
0  apple      0
1   ball      1
2  apple      2
3  apple      3
4   ball      4
5    cat      5

In [39]:
right1

group_val
apple       33.4
ball         5.0

In [40]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer')

key  value  group_val
0  apple      0       33.4
2  apple      2       33.4
3  apple      3       33.4
1   ball      1        5.0
4   ball      4        5.0
5    cat      5        NaN

In [41]:
pd.merge(left1, right1, left_on='key', right_index=True, how="inner")

key  value  group_val
0  apple      0       33.4
2  apple      2       33.4
3  apple      3       33.4
1   ball      1        5.0
4   ball      4        5.0

In [43]:
pd.merge(left1, right1, left_on='key', right_index=True, how="right")

key  value  group_val
0  apple      0       33.4
2  apple      2       33.4
3  apple      3       33.4
1   ball      1        5.0
4   ball      4        5.0

### Résumé:
> - Suivant le nom des colonnes, on peut aussi avoir:
>   - right_on = ..., left_index = ....    

# 4. Echantillonnage