# MODIFICATION & TRANSFORMATION DES DONNEES
### => ou Etapde de Pre processing
#### => On parle aussi de Préparation ou Pré traitement des données

In [3]:
# NB : il est à noter que Numpy tourne sur le CPU et non sur le GPU

In [6]:
import numpy as np
import pandas as pd

In [7]:
# Importation du fichier movie

dossier = '/home/simplon/Documents/4_PYTHON_Bases/SYNTH_2_ANALYSE_DATASET/Datasets'
dossier + '/movie.csv'
movie = pd.read_csv(dossier + '/movie.csv')

In [8]:
cols_interest = ["director_name", "duration", "gross", "genres",
                 'movie_title', "plot_keywords","budget", "title_year", "language", "imdb_score"]
movie_reduced = movie[cols_interest]

# 1. Suppression de données 

## 1.1. Chercher et supprimer doublons avec `.duplicated()` et `.drop_duplicates()`

In [9]:
# Création du dataframe frame3 comportant des doublons

frame3 = pd.DataFrame({'column 1': ['Looping'] * 3 + ['Functions'] * 4, 
                       'column 2': [10, 10, 22, 23, 23, 24, 24]})
frame3

column 1  column 2
0    Looping        10
1    Looping        10
2    Looping        22
3  Functions        23
4  Functions        23
5  Functions        24
6  Functions        24

In [10]:
# Rechercher les doublons avec .duplicated()

frame3.duplicated()

0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [11]:
frame3.duplicated().value_counts()  # True = > Duplicate

False    4
True     3
dtype: int64

In [12]:
# Supprimer les doublons avec .drop_duplicates()

frame3.drop_duplicates()

column 1  column 2
0    Looping        10
2    Looping        22
3  Functions        23
5  Functions        24

In [13]:
# Réinitialiser l'index avec .reset_index(drop=True)

frame3.drop_duplicates().reset_index() # Résultat renvoyé par défaut => drop = False

index   column 1  column 2
0      0    Looping        10
1      2    Looping        22
2      3  Functions        23
3      5  Functions        24

In [14]:
frame3.drop_duplicates().reset_index(drop=True)

column 1  column 2
0    Looping        10
1    Looping        22
2  Functions        23
3  Functions        24

In [16]:
# Création d'une 3ième colonne

frame3['col3'] = range(7)
frame3

column 1  column 2  col3
0    Looping        10     0
1    Looping        10     1
2    Looping        22     2
3  Functions        23     3
4  Functions        23     4
5  Functions        24     5
6  Functions        24     6

In [15]:
# Suppression des duplicates par rapport à une colonne donnée
    
frame3.drop_duplicates(['column 2']).reset_index(drop=True)

column 1  column 2  col3
0    Looping        10     0
1    Looping        22     2
2  Functions        23     3
3  Functions        24     5

In [83]:
# Suppression des duplicates par rapport à une colonne et une occurence données

frame3.drop_duplicates(['column 1'], keep='last').reset_index(drop=True)

    # keep = first ou last ou False; par défaut c'est first cad si keep pas précisé

column 1  column 2  col3
0    Looping        22     2
1  Functions        24     6

## 1.2. Suppression de lignes ou de colonnes du dataset avec `.drop()` & `axis = ..`

In [10]:
movie_reduced.head(5)

director_name  duration        gross                           genres  \
0      James Cameron     178.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1     Gore Verbinski     169.0  309404152.0         Action|Adventure|Fantasy   
2         Sam Mendes     148.0  200074175.0        Action|Adventure|Thriller   
3  Christopher Nolan     164.0  448130642.0                  Action|Thriller   
4        Doug Walker       NaN          NaN                      Documentary   

                                  movie_title  \
0                                      Avatar   
1    Pirates of the Caribbean: At World's End   
2                                     Spectre   
3                       The Dark Knight Rises   
4  Star Wars: Episode VII - The Force Awakens   

                                       plot_keywords       budget  title_year  \
0             avatar|future|marine|native|paraplegic  237000000.0      2009.0   
1  goddess|marriage ceremony|marriage proposal|pi...  300000000.0      2007.0   
2                bomb|espionage|sequel|spy|terrorist  245000000.0      2015.0   
3  deception|imprisonment|lawlessness|police offi...  250000000.0      2012.0   
4                                                NaN          NaN         NaN   

  language  imdb_score  
0  English         7.9  
1  English         7.1  
2  English         6.8  
3  English         8.5  
4      NaN         7.1

In [27]:
# Suppression de la première ligne

movie_reduced.drop(0).head(5)

director_name  duration        gross                     genres  \
1     Gore Verbinski     169.0  309404152.0   Action|Adventure|Fantasy   
2         Sam Mendes     148.0  200074175.0  Action|Adventure|Thriller   
3  Christopher Nolan     164.0  448130642.0            Action|Thriller   
4        Doug Walker       NaN          NaN                Documentary   
5     Andrew Stanton     132.0   73058679.0    Action|Adventure|Sci-Fi   

                                  movie_title  \
1    Pirates of the Caribbean: At World's End   
2                                     Spectre   
3                       The Dark Knight Rises   
4  Star Wars: Episode VII - The Force Awakens   
5                                 John Carter   

                                       plot_keywords       budget  title_year  \
1  goddess|marriage ceremony|marriage proposal|pi...  300000000.0      2007.0   
2                bomb|espionage|sequel|spy|terrorist  245000000.0      2015.0   
3  deception|imprisonment|lawlessness|police offi...  250000000.0      2012.0   
4                                                NaN          NaN         NaN   
5  alien|american civil war|male nipple|mars|prin...  263700000.0      2012.0   

  language  imdb_score  
1  English         7.1  
2  English         6.8  
3  English         8.5  
4      NaN         7.1  
5  English         6.6

In [31]:
# Suppression de plusieurs lignes

movie_reduced.drop([2, 4], axis=0).head(5)

director_name  duration        gross                           genres  \
0      James Cameron     178.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1     Gore Verbinski     169.0  309404152.0         Action|Adventure|Fantasy   
3  Christopher Nolan     164.0  448130642.0                  Action|Thriller   
5     Andrew Stanton     132.0   73058679.0          Action|Adventure|Sci-Fi   
6          Sam Raimi     156.0  336530303.0         Action|Adventure|Romance   

                                movie_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
3                     The Dark Knight Rises   
5                               John Carter   
6                              Spider-Man 3   

                                       plot_keywords       budget  title_year  \
0             avatar|future|marine|native|paraplegic  237000000.0      2009.0   
1  goddess|marriage ceremony|marriage proposal|pi...  300000000.0      2007.0   
3  deception|imprisonment|lawlessness|police offi...  250000000.0      2012.0   
5  alien|american civil war|male nipple|mars|prin...  263700000.0      2012.0   
6          sandman|spider man|symbiote|venom|villain  258000000.0      2007.0   

  language  imdb_score  
0  English         7.9  
1  English         7.1  
3  English         8.5  
5  English         6.6  
6  English         6.2

In [18]:
# Suppression d'une colonne

movie_reduced.drop(['director_name'], axis=1).head(5)

duration        gross                           genres  \
0     178.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1     169.0  309404152.0         Action|Adventure|Fantasy   
2     148.0  200074175.0        Action|Adventure|Thriller   
3     164.0  448130642.0                  Action|Thriller   
4       NaN          NaN                      Documentary   

                                  movie_title  \
0                                      Avatar   
1    Pirates of the Caribbean: At World's End   
2                                     Spectre   
3                       The Dark Knight Rises   
4  Star Wars: Episode VII - The Force Awakens   

                                       plot_keywords       budget  title_year  \
0             avatar|future|marine|native|paraplegic  237000000.0      2009.0   
1  goddess|marriage ceremony|marriage proposal|pi...  300000000.0      2007.0   
2                bomb|espionage|sequel|spy|terrorist  245000000.0      2015.0   
3  deception|imprisonment|lawlessness|police offi...  250000000.0      2012.0   
4                                                NaN          NaN         NaN   

  language  imdb_score  
0  English         7.9  
1  English         7.1  
2  English         6.8  
3  English         8.5  
4      NaN         7.1

In [67]:
# Suppression de plusieurs colonnes

movie_reduced.drop(['director_name', 'duration'], axis=1).head(5)

gross                           genres  \
0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1  309404152.0         Action|Adventure|Fantasy   
2  200074175.0        Action|Adventure|Thriller   
3  448130642.0                  Action|Thriller   
4          NaN                      Documentary   

                                  movie_title  \
0                                      Avatar   
1    Pirates of the Caribbean: At World's End   
2                                     Spectre   
3                       The Dark Knight Rises   
4  Star Wars: Episode VII - The Force Awakens   

                                       plot_keywords       budget  title_year  \
0             avatar|future|marine|native|paraplegic  237000000.0      2009.0   
1  goddess|marriage ceremony|marriage proposal|pi...  300000000.0      2007.0   
2                bomb|espionage|sequel|spy|terrorist  245000000.0      2015.0   
3  deception|imprisonment|lawlessness|police offi...  250000000.0      2012.0   
4                                                NaN          NaN         NaN   

  language  imdb_score  
0  English         7.9  
1  English         7.1  
2  English         6.8  
3  English         8.5  
4      NaN         7.1

# 2. Modifier les valeurs d'un Dataframe

## 2.1. Renommage de colonne(s) avec `.rename(columns = {'...' : '...'})`

In [108]:
movie.head()

color      director_name  num_critic_for_reviews  duration  \
0  Color      James Cameron                   723.0     178.0   
1  Color     Gore Verbinski                   302.0     169.0   
2  Color         Sam Mendes                   602.0     148.0   
3  Color  Christopher Nolan                   813.0     164.0   
4    NaN        Doug Walker                     NaN       NaN   

   director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                      0.0                   855.0  Joel David Moore   
1                    563.0                  1000.0     Orlando Bloom   
2                      0.0                   161.0      Rory Kinnear   
3                  22000.0                 23000.0    Christian Bale   
4                    131.0                     NaN        Rob Walker   

   actor_1_facebook_likes        gross                           genres  ...  \
0                  1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi  ...   
1                 40000.0  309404152.0         Action|Adventure|Fantasy  ...   
2                 11000.0  200074175.0        Action|Adventure|Thriller  ...   
3                 27000.0  448130642.0                  Action|Thriller  ...   
4                   131.0          NaN                      Documentary  ...   

  num_user_for_reviews language  country  content_rating       budget  \
0               3054.0  English      USA           PG-13  237000000.0   
1               1238.0  English      USA           PG-13  300000000.0   
2                994.0  English       UK           PG-13  245000000.0   
3               2701.0  English      USA           PG-13  250000000.0   
4                  NaN      NaN      NaN             NaN          NaN   

   title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0      2009.0                  936.0        7.9          1.78   
1      2007.0                 5000.0        7.1          2.35   
2      2015.0                  393.0        6.8          2.35   
3      2012.0                23000.0        8.5          2.35   
4         NaN                   12.0        7.1           NaN   

  movie_facebook_likes  
0                33000  
1                    0  
2                85000  
3               164000  
4                    0  

[5 rows x 28 columns]

In [ ]:
# Renommer une colonne

In [109]:
    # => dataset.rename(colomns = {'nomColonneCconcernee' : 'nomColonneNouvelle'})
    
movie.rename(columns = {'director_facebook_likes' : 'director_fb_likes'}) # avec inplace=True => modifie original

In [110]:
movie.head()

color      director_name  num_critic_for_reviews  duration  \
0  Color      James Cameron                   723.0     178.0   
1  Color     Gore Verbinski                   302.0     169.0   
2  Color         Sam Mendes                   602.0     148.0   
3  Color  Christopher Nolan                   813.0     164.0   
4    NaN        Doug Walker                     NaN       NaN   

   director_fb_likes  actor_3_facebook_likes      actor_2_name  \
0                0.0                   855.0  Joel David Moore   
1              563.0                  1000.0     Orlando Bloom   
2                0.0                   161.0      Rory Kinnear   
3            22000.0                 23000.0    Christian Bale   
4              131.0                     NaN        Rob Walker   

   actor_1_facebook_likes        gross                           genres  ...  \
0                  1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi  ...   
1                 40000.0  309404152.0         Action|Adventure|Fantasy  ...   
2                 11000.0  200074175.0        Action|Adventure|Thriller  ...   
3                 27000.0  448130642.0                  Action|Thriller  ...   
4                   131.0          NaN                      Documentary  ...   

  num_user_for_reviews language  country  content_rating       budget  \
0               3054.0  English      USA           PG-13  237000000.0   
1               1238.0  English      USA           PG-13  300000000.0   
2                994.0  English       UK           PG-13  245000000.0   
3               2701.0  English      USA           PG-13  250000000.0   
4                  NaN      NaN      NaN             NaN          NaN   

   title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0      2009.0                  936.0        7.9          1.78   
1      2007.0                 5000.0        7.1          2.35   
2      2015.0                  393.0        6.8          2.35   
3      2012.0                23000.0        8.5          2.35   
4         NaN                   12.0        7.1           NaN   

  movie_facebook_likes  
0                33000  
1                    0  
2                85000  
3               164000  
4                    0  

[5 rows x 28 columns]

In [ ]:
# Renommer plusieurs colonnes

## 2.2. Céation de lignes ou de colonnes

In [99]:
# Créer une copie de movie_reduced pour en faire un jeu de donnés pour la pratique

practics = movie_reduced.copy()
practics.head()

director_name  duration        gross                           genres  \
0      James Cameron     178.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1     Gore Verbinski     169.0  309404152.0         Action|Adventure|Fantasy   
2         Sam Mendes     148.0  200074175.0        Action|Adventure|Thriller   
3  Christopher Nolan     164.0  448130642.0                  Action|Thriller   
4        Doug Walker       NaN          NaN                      Documentary   

                                  movie_title  \
0                                      Avatar   
1    Pirates of the Caribbean: At World's End   
2                                     Spectre   
3                       The Dark Knight Rises   
4  Star Wars: Episode VII - The Force Awakens   

                                       plot_keywords       budget  title_year  \
0             avatar|future|marine|native|paraplegic  237000000.0      2009.0   
1  goddess|marriage ceremony|marriage proposal|pi...  300000000.0      2007.0   
2                bomb|espionage|sequel|spy|terrorist  245000000.0      2015.0   
3  deception|imprisonment|lawlessness|police offi...  250000000.0      2012.0   
4                                                NaN          NaN         NaN   

  language  imdb_score  
0  English         7.9  
1  English         7.1  
2  English         6.8  
3  English         8.5  
4      NaN         7.1

### 2.2.1. Créer une ou plusieurs lignes

In [ ]:
# Créer une ligne

In [ ]:
# Créer plusieurs lignes

### 2.2.2. Créer une ou plusieurs colonnes

In [109]:
practics.index

RangeIndex(start=0, stop=4916, step=1)

In [108]:
# Créer une colonne => practics['nomNvelVariab'] = [lesValeurs affectées à la nvl var]

practics['Prix_Jour'] = np.arange(100, 5016)
practics['Prix_Jour']

0        100
1        101
2        102
3        103
4        104
        ... 
4911    5011
4912    5012
4913    5013
4914    5014
4915    5015
Name: Prix_Jour, Length: 4916, dtype: int64

In [113]:
practics['Côte'] = 'femme'

In [114]:
practics

director_name  duration        gross  \
0         James Cameron     178.0  760505847.0   
1        Gore Verbinski     169.0  309404152.0   
2            Sam Mendes     148.0  200074175.0   
3     Christopher Nolan     164.0  448130642.0   
4           Doug Walker       NaN          NaN   
...                 ...       ...          ...   
4911        Scott Smith      87.0          NaN   
4912                NaN      43.0          NaN   
4913   Benjamin Roberds      76.0          NaN   
4914        Daniel Hsia     100.0      10443.0   
4915           Jon Gunn      90.0      85222.0   

                               genres  \
0     Action|Adventure|Fantasy|Sci-Fi   
1            Action|Adventure|Fantasy   
2           Action|Adventure|Thriller   
3                     Action|Thriller   
4                         Documentary   
...                               ...   
4911                     Comedy|Drama   
4912     Crime|Drama|Mystery|Thriller   
4913            Drama|Horror|Thriller   
4914             Comedy|Drama|Romance   
4915                      Documentary   

                                     movie_title  \
0                                         Avatar   
1       Pirates of the Caribbean: At World's End   
2                                        Spectre   
3                          The Dark Knight Rises   
4     Star Wars: Episode VII - The Force Awakens   
...                                          ...   
4911                     Signed Sealed Delivered   
4912                               The Following   
4913                        A Plague So Pleasant   
4914                            Shanghai Calling   
4915                           My Date with Drew   

                                          plot_keywords       budget  \
0                avatar|future|marine|native|paraplegic  237000000.0   
1     goddess|marriage ceremony|marriage proposal|pi...  300000000.0   
2                   bomb|espionage|sequel|spy|terrorist  245000000.0   
3     deception|imprisonment|lawlessness|police offi...  250000000.0   
4                                                   NaN          NaN   
...                                                 ...          ...   
4911             fraud|postal worker|prison|theft|trial          NaN   
4912       cult|fbi|hideout|prison escape|serial killer          NaN   
4913                                                NaN       1400.0   
4914                                                NaN          NaN   
4915  actress name in title|crush|date|four word tit...       1100.0   

      title_year language  imdb_score  Prix_Jour   Côte  
0         2009.0  English         7.9        100  femme  
1         2007.0  English         7.1        101  femme  
2         2015.0  English         6.8        102  femme  
3         2012.0  English         8.5        103  femme  
4            NaN      NaN         7.1        104  femme  
...          ...      ...         ...        ...    ...  
4911      2013.0  English         7.7       5011  femme  
4912         NaN  English         7.5       5012  femme  
4913      2013.0  English         6.3       5013  femme  
4914      2012.0  English         6.3       5014  femme  
4915      2004.0  English         6.6       5015  femme  

[4916 rows x 12 columns]

In [ ]:
# Créer plusieurs colonnes

In [122]:
# practics['reference', 'appreciation'] = (('A', 'top')) ??

### Sources à explorer pour insertion lignes et colonnes
http://www.python-simple.com/python-pandas/modif-dataframes.php

https://prograide.com/pregunta/48233/ajout-simultane-de-plusieurs-colonnes--des-pandas

## 2.3. Modification des données par le replacing 
> Permet de modifier les occurences d'une valeur donnée 

### 2.3.1. Le replacing des données avec `.replace(to_replace=.., value=..)`

In [12]:
frame3

column 1  column 2  col3
0    Looping        10     0
1    Looping        10     1
2    Looping        22     2
3  Functions        23     3
4  Functions        23     4
5  Functions        24     5
6  Functions        24     6

In [50]:
# 1 / Modification appliquée à l'ensemble du dataset

frame3.replace(to_replace=23, value=np.nan)

frame4 = frame3.replace(to_replace=23, value=np.nan)
frame4

column 1  column 2  col3
0    Looping      10.0     0
1    Looping      10.0     1
2    Looping      22.0     2
3  Functions       NaN     3
4  Functions       NaN     4
5  Functions      24.0     5
6  Functions      24.0     6

In [24]:
# 2/ Modification appliquée sur plusieurs valeurs de l'ensemble du dataset
frame3

column 1  column 2  col3
0    Looping        10     0
1    Looping        10     1
2    Looping        22     2
3  Functions        23     3
4  Functions        23     4
5  Functions        24     5
6  Functions        24     6

In [52]:
    # Remplacer les 10 et les 23 respectivement par les chiffres 1 et 2
frame3               

column 1  column 2  col3
0    Looping        10     0
1    Looping        10     1
2    Looping        22     2
3  Functions        23     3
4  Functions        23     4
5  Functions        24     5
6  Functions        24     6

In [53]:
frame3.replace(to_replace = [10, 23], value = [1, 2])

column 1  column 2  col3
0    Looping         1     0
1    Looping         1     1
2    Looping        22     2
3  Functions         2     3
4  Functions         2     4
5  Functions        24     5
6  Functions        24     6

In [51]:
# 3 / Modification appliquée sur une seule colonne

frame4['column 2'].replace(to_replace=np.nan, value=-8)

0    10.0
1    10.0
2    22.0
3    -8.0
4    -8.0
5    24.0
6    24.0
Name: column 2, dtype: float64

### 2.3.2. Le replacing des données avec `.iat` et `.at`
> => Permet de remplacer une valeur précise par son index ou par son nom

In [54]:
frame3

column 1  column 2  col3
0    Looping        10     0
1    Looping        10     1
2    Looping        22     2
3  Functions        23     3
4  Functions        23     4
5  Functions        24     5
6  Functions        24     6

In [58]:
# Rappels pour sélectionner le chiffre 3 :

frame3.iloc[3, 2]

frame3.loc[3, 'col3']

3

In [61]:
# Application
    
    # Remplacer 3 par 12 000 avec .iat

frame3.iat[3,2] = 12000
frame3

column 1  column 2   col3
0    Looping        10      0
1    Looping        10      1
2    Looping        22      2
3  Functions        23  12000
4  Functions        23      4
5  Functions        24      5
6  Functions        24      6

In [63]:
    # Remplacer 4 par 25 000  avec .at
frame3.at[4, 'col3'] = 25000
frame3

column 1  column 2   col3
0    Looping        10      0
1    Looping        10      1
2    Looping        22      2
3  Functions        23  12000
4  Functions        23  25000
5  Functions        24      5
6  Functions        24      6

## 2.4. Modiffication du dataframe par reshaping & pivoting

### 2.4.1. Modifier la taille du tableau avec `.reshape()`

In [41]:
dataExp = np.array([[1, 3, 5, 7, 9, 11],
              [2, 6, 8, 10, 12, 14]])
dataExp

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  6,  8, 10, 12, 14]])

In [39]:
dataExp.shape

(2, 6)

In [40]:
dataExp.size

12

In [44]:
dataExp.reshape((6,2))  # Cdt°: le reshape doit avoir le même nb d'élts (size) que le précédent soit 6 x 2 = 12

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [ 2,  6],
       [ 8, 10],
       [12, 14]])

In [45]:
dataExp.reshape((4,3))   # soit également 4 x3 = 12

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [ 2,  6,  8],
       [10, 12, 14]])

In [ ]:
# Cas particulier

In [46]:
x = np.array([1, 3, 5])

In [47]:
x.shape

(3,)

In [48]:
x.reshape((3,1))

array([[1],
       [3],
       [5]])

### 2.4.2. Pivoter les données avec `.stack()`

In [21]:
# Soit data le dataframe représentatnt des données (observations) de pluie, d'humidité et de vent par villes

data = np.arange(15).reshape((3,5))
indexers = ['Rainfall', 'Humidity', 'Wind']
dframe1 = pd.DataFrame(data, index=indexers, columns=['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Kristiansand'])
dframe1

# NB : dans un Dataframe :
    # Chaque Variable est représentée par une COLONNE
    # Chaque Observation est représentée par une LIGNE

# Ce qui n'est pas le cas pour ce dataframe d'où le pivoting

Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

In [24]:
# Opération de verticalisation des colonnes et horizontalisation des lignes

hygrometry = dframe1.stack()
hygrometry

Rainfall  Bergen           0
          Oslo             1
          Trondheim        2
          Stavanger        3
          Kristiansand     4
Humidity  Bergen           5
          Oslo             6
          Trondheim        7
          Stavanger        8
          Kristiansand     9
Wind      Bergen          10
          Oslo            11
          Trondheim       12
          Stavanger       13
          Kristiansand    14
dtype: int64

In [25]:
    # Re-définition de l'index => indexation des observations & MEP des libellés par colonne pour les variables
    
hygrometry.reset_index()

level_0       level_1   0
0   Rainfall        Bergen   0
1   Rainfall          Oslo   1
2   Rainfall     Trondheim   2
3   Rainfall     Stavanger   3
4   Rainfall  Kristiansand   4
5   Humidity        Bergen   5
6   Humidity          Oslo   6
7   Humidity     Trondheim   7
8   Humidity     Stavanger   8
9   Humidity  Kristiansand   9
10      Wind        Bergen  10
11      Wind          Oslo  11
12      Wind     Trondheim  12
13      Wind     Stavanger  13
14      Wind  Kristiansand  14

In [ ]:
# Renommer les colonnes => A faire ....!

In [27]:
# Revenir à l'état initial avec < dataframe.unstack() >

hygrometry.unstack()

Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

## 2.5. Modifications de valeurs suivant les lignes ou les colonnes avec `axis`
Le concept de l'axis s'applique de la même façon aux tableaux Numpy et Pandas

In [78]:
dfx

store1  store2  store3  store4  store5
apple         15.0    16.0    17.0     NaN     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
orange        15.0    16.0    17.0    18.0     NaN
strawberry     NaN     NaN     NaN     NaN     NaN

### 2.5.1. Suppressions de valeurs manquantes avec `axis = 0` ou `axis = 1`

In [79]:
dfx.dropna(how='all', axis=0)     # => Suppression des LIGNES comportant que des NaN (strawberry)

store1  store2  store3  store4  store5
apple     15.0    16.0    17.0     NaN     NaN
banana    18.0    19.0    20.0     NaN     NaN
kiwi      21.0    22.0    23.0     NaN     NaN
grapes    24.0    25.0    26.0     NaN     NaN
mango     27.0    28.0    29.0     NaN     NaN
orange    15.0    16.0    17.0    18.0     NaN

In [106]:
dfx.dropna(how='all', axis=1)       # => Suppression des COLONNES comportant que des NaN (store5)

store1  store2  store3  store4
apple         15.0    16.0    17.0     NaN
banana        18.0    19.0    20.0     NaN
kiwi          21.0    22.0    23.0     NaN
grapes        24.0    25.0    26.0     NaN
mango         27.0    28.0    29.0     NaN
orange        15.0    16.0    17.0    18.0
strawberry     NaN     NaN     NaN     NaN

### 2.5.2. Calculs avec `axis = 0` ou `axis = 1`

In [ ]:
# Exemple 1

In [107]:
dfx.mean(axis = 0)            # => Moyenne des valeurs de chaque colonne (opt° par défaut)

store1    20.0
store2    21.0
store3    22.0
store4    18.0
store5     NaN
dtype: float64

In [108]:
dfx.mean(axis = 1)           # => Mooyenne des valeurs de chaque ligne

apple         16.0
banana        19.0
kiwi          22.0
grapes        25.0
mango         28.0
orange        16.5
strawberry     NaN
dtype: float64

In [ ]:
# Exemple 2

In [32]:
    # Modiffications des colonnes et lignes

In [68]:
tab = np.array([[12,  5,  0],
                [ 3, 11,  3],
                [ 7,  9,  3],
                [ 5,  2,  4],
                [ 7,  6,  8]])
tab

array([[12,  5,  0],
       [ 3, 11,  3],
       [ 7,  9,  3],
       [ 5,  2,  4],
       [ 7,  6,  8]])

In [36]:
np.min(tab, axis=0)      # Minimum de chaque colonne 

#tab.min(axis=0)

array([3, 2, 0])

In [37]:
np.min(tab, axis=1)      # Minimum de chaque ligne 

array([0, 3, 3, 2, 6])

In [38]:
np.mean(tab, axis= 1)    # Moyenne de chaque ligne

array([5.66666667, 5.66666667, 6.33333333, 3.66666667, 7.        ])

In [39]:
np.sum(tab, axis= 0)     # somme de chque colonne

array([34, 33, 18])

In [ ]:
Pour axis = 0, nous appliquons une fonction le long de chaque «colonne», ou 
de toutes les valeurs qui apparaissent verticalement.

In [ ]:
Pour axis = 1, nous appliquons une fonction le long de chaque «ligne», ou 
de toutes les valeurs horizontalement.

In [ ]:
# Synthèse perso:
    # Pour les suppressions => cf shape(x,y) où shape[0] = nb lignes (x) & shape[1] = nb colonnes (y)
        # axis = 0 => lignes  &   axis = 1 / axis = 'columns' => colonnes
        
    # Pour les calculs => inverse du concept shape : 0 >> colonne & 1 >> ligne => Se réferer au schémas slides
        # axis = 0 => calcul suivant chaque colonne  &  axis = 1 => calcul suivant chaque ligne

# Rapide et robuste  //  Audace et résiliance cf. Régis Nègre

## 2.6. La conversion des types de données

In [ ]:
### 2.6.1 conversion 

In [ ]:
# avec .astype()

In [90]:
# conversion liste en numpy array

ls =[1, 2, 3]

In [92]:
arr = np.array(ls)
arr

array([1, 2, 3])

## 2.6. Gestion des valeurs manquantes

In [ ]:
# A remonter ici

# 3. Transformation des valeurs d'un Dataframe

## 3.1. Transformation des variables numériques en catégorielles et inversement

### 3.1.1. Transformer les variables numériques en variables catégorielles avec `pd.cut()`

In [28]:
# la liste de notes

notes = np.random.randint(20, size=(15,)).tolist()
notes

[14, 8, 10, 0, 5, 7, 3, 14, 0, 11, 19, 11, 1, 12, 4]

In [29]:
# Définition des bornes
bins = [-1, 10, 12, 15, 18, 20]

In [30]:
# Déterminons les intervalles
bins_names = ['échoué', 'passable', 'assez-bien', 'bien', 'très bien']

In [33]:
category = pd.cut(notes, bins, right=False, labels=bins_names).tolist()
category

# right = False => les bornes sup st ouvertes donc 12 aura le label assez-bien et non passable !

['assez-bien',
 'échoué',
 'passable',
 'échoué',
 'échoué',
 'échoué',
 'échoué',
 'assez-bien',
 'échoué',
 'passable',
 'très bien',
 'passable',
 'échoué',
 'assez-bien',
 'échoué']

### 3.1.2. Transformer les variables catégorielles en variables numériques avec ` `

In [ ]:
# Création du dataframe illustratif

# dataDemo1 = 

In [ ]:
data['sexe'].map({'female:0', 'male:1'}) 

In [ ]:
data['sexe'].replace(['female', 'male'], [0, 1])

In [ ]:
data['sexe'].astype()'category').cat.codes

## 3.2. Autres transformations avec Numpy et Pandas

## 3.3. Transformation des variables avec `Scikit Learn`

In [ ]:
# Voir noteBook : Transformation_Données_Pre-Processing_

### 3.2.1. Transformation des variables `quantitatives`

#### 3.2.1.1. La normalisation

**1. Fit & Transform avec `MinMaxScaler` => Rescaler**

#### 3.2.1.2. Feature ingeneering

### 3.2.2. Transformation des variables `qualitatives` 

## 3.2. Normalisation des données d'un Dataframe

# 4. Gestion des valeurs manquantes

In [64]:
# Soit le dataframe dfx :

data = np.arange(15, 30).reshape(5, 3)
dfx = pd.DataFrame(data, index=['apple', 'banana', 'kiwi',
'grapes', 'mango'], columns=['store1', 'store2', 'store3'])
dfx

store1  store2  store3
apple       15      16      17
banana      18      19      20
kiwi        21      22      23
grapes      24      25      26
mango       27      28      29

In [65]:
# Préparation du dataset de démonstration
    # Insertion d'une nouvelle colonne store4 comportant des Numpy NaN

dfx['store4'] = np.nan
dfx

store1  store2  store3  store4
apple       15      16      17     NaN
banana      18      19      20     NaN
kiwi        21      22      23     NaN
grapes      24      25      26     NaN
mango       27      28      29     NaN

In [66]:
    # Création d'une ligne dans le tableau dfx avec .loc

dfx.loc['orange'] = np.arange(15, 19)
dfx

store1  store2  store3  store4
apple       15      16      17     NaN
banana      18      19      20     NaN
kiwi        21      22      23     NaN
grapes      24      25      26     NaN
mango       27      28      29     NaN
orange      15      16      17    18.0

In [67]:
    # Création d'une ligne et d'une colonne de valeurs manquantes NaN

        # Création de la ligne
dfx.loc['strawberry'] = np.nan
dfx

        # Création de la colonne
dfx['store5'] = np.nan
dfx

store1  store2  store3  store4  store5
apple         15.0    16.0    17.0     NaN     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
orange        15.0    16.0    17.0    18.0     NaN
strawberry     NaN     NaN     NaN     NaN     NaN

## 4.1. Supprimer les valeurs manquantes avec `.dropna()` & `axis=..`

In [70]:
dfx.dropna()                 # => Supprime toutes les lignes comportant au moins une valeur maquante

Empty DataFrame
Columns: [store1, store2, store3, store4, store5]
Index: []

In [72]:
dfx.dropna(how='all')     # => Supprimes les lignes comport que des valeurs manquantes => (.., axis = 0 par défaut)

store1  store2  store3  store4  store5
apple     15.0    16.0    17.0     NaN     NaN
banana    18.0    19.0    20.0     NaN     NaN
kiwi      21.0    22.0    23.0     NaN     NaN
grapes    24.0    25.0    26.0     NaN     NaN
mango     27.0    28.0    29.0     NaN     NaN
orange    15.0    16.0    17.0    18.0     NaN

In [73]:
dfx.dropna(how='all', axis=1)    # => Supprime les colonnes comportant que des valeurs manquantes

store1  store2  store3  store4
apple         15.0    16.0    17.0     NaN
banana        18.0    19.0    20.0     NaN
kiwi          21.0    22.0    23.0     NaN
grapes        24.0    25.0    26.0     NaN
mango         27.0    28.0    29.0     NaN
orange        15.0    16.0    17.0    18.0
strawberry     NaN     NaN     NaN     NaN

In [80]:
# Limitter la suppression des valeurs manquantes à un seuil

dfx.dropna(thresh=6, axis=1)  # => Supprime les colonnes ayant un nb de NaN >= au seuil (thresh)

store1  store2  store3
apple         15.0    16.0    17.0
banana        18.0    19.0    20.0
kiwi          21.0    22.0    23.0
grapes        24.0    25.0    26.0
mango         27.0    28.0    29.0
orange        15.0    16.0    17.0
strawberry     NaN     NaN     NaN

## 4.2. Remplacer les valeurs manquantes 

### 4.2.1. Remplacer les valeurs manquantes avec `.fillna()` 

In [100]:
dfx.fillna(0)    # => Remplace toutes les valeurs manquantes par 0

store1  store2  store3  store4  store5
apple         15.0    16.0    17.0     0.0     0.0
banana        18.0    19.0    20.0     0.0     0.0
kiwi          21.0    22.0    23.0     0.0     0.0
grapes        24.0    25.0    26.0     0.0     0.0
mango         27.0    28.0    29.0     0.0     0.0
orange        15.0    16.0    17.0    18.0     0.0
strawberry     0.0     0.0     0.0     0.0     0.0

In [110]:
dfx.mean()

store1    20.0
store2    21.0
store3    22.0
store4    18.0
store5     NaN
dtype: float64

In [115]:
dfx.fillna(dfx.mean())   # => Remplace toutes les valeurs manquantes par la moyenne de la colonne correspondante

# NB : on peut remplacer également par la médiane / la valeure la plus fréquente

store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    18.0     NaN
banana        18.0    19.0    20.0    18.0     NaN
kiwi          21.0    22.0    23.0    18.0     NaN
grapes        24.0    25.0    26.0    18.0     NaN
mango         27.0    28.0    29.0    18.0     NaN
orange        15.0    16.0    17.0    18.0     NaN
strawberry    20.0    21.0    22.0    18.0     NaN

### 4.2.2. Remplacer les valeurs manquantes avec `.fillna(method='ffill')` ou  `..(method='bfill')`
> S'appliquent surtout aux series temporelles

In [102]:
dfx

store1  store2  store3  store4  store5
apple         15.0    16.0    17.0     NaN     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
orange        15.0    16.0    17.0    18.0     NaN
strawberry     NaN     NaN     NaN     NaN     NaN

In [118]:
# Remplacer les valeurs manquantes avec forward filling

dfx.store4.fillna(method='ffill')  # Remplacer la/les NaN situées immédiatement en dessous d'une valeur notée
                                       # par cette même valeur
                                           # => NaN positionnée immédiatement en dessous de la valeur notée est
                                               # remplacée par celle-ci

apple          NaN
banana         NaN
kiwi           NaN
grapes         NaN
mango          NaN
orange        18.0
strawberry    18.0
Name: store4, dtype: float64

In [119]:
# Remplacer les valeurs manquantes avec backward filling

dfx.store4.fillna(method='bfill')   # Remplacer la/les NaN situées immédiatement au dessus d'une valeur notée 
                                        # par cette même valeur
                                            # => NaN positionné immédiatement au dessus de la valeur notée est 
                                                # remplacé par celle-ci 


apple         18.0
banana        18.0
kiwi          18.0
grapes        18.0
mango         18.0
orange        18.0
strawberry     NaN
Name: store4, dtype: float64

### 4.2.3. Remplacer les valeurs manquantes par interpolation avec `.interpolate()`

In [82]:
# interpoler les valeurs manquantes

n_ventes = pd.Series([100, np.nan, np.nan, 200, np.nan, 150])
n_ventes

0    100.0
1      NaN
2      NaN
3    200.0
4      NaN
5    150.0
dtype: float64

In [83]:
n_ventes.interpolate()

0    100.000000
1    133.333333
2    166.666667
3    200.000000
4    175.000000
5    150.000000
dtype: float64

## Divers modifications à reclasser

**Concatener des tableaux**

In [2]:
x = np.array([1, 3, 5])

In [3]:
y = np.array([2, 6, 8])

In [4]:
np.hstack([x, y])

array([1, 3, 5, 2, 6, 8])

In [5]:
np.vstack([x, y])

array([[1, 3, 5],
       [2, 6, 8]])

In [6]:
x1 = np.array([[1, 3, 5], [2, 6, 8]])

In [7]:
x1

array([[1, 3, 5],
       [2, 6, 8]])

In [8]:
y1 = np.array([[11, 13, 15], [10, 12, 14]])

In [9]:
y1

array([[11, 13, 15],
       [10, 12, 14]])

In [10]:
np.hstack([x1, y1])

array([[ 1,  3,  5, 11, 13, 15],
       [ 2,  6,  8, 10, 12, 14]])

In [11]:
np.vstack([x1, y1])

array([[ 1,  3,  5],
       [ 2,  6,  8],
       [11, 13, 15],
       [10, 12, 14]])

### Calculs statistiques sur les tableaux avec numpy

**Calcul avec les vecteurs**

**Calcul avec les tableaux numpy (matrices)**

In [13]:
# Modiffications des colonnes et lignes

In [85]:
l = [5, 8, 9]

In [86]:
type(l)

list

In [88]:
m = np.array([5, 8, 9])

In [89]:
type(m)

numpy.ndarray

In [15]:
min(l)

5

In [16]:
np.min(l)

5

In [18]:
min(m)

5

In [19]:
np.min(m)

5

In [23]:
np.array(m).min()

5

In [30]:
tab = np.array([[12,  5,  0],
                [ 3, 11,  3],
                [ 7,  9,  3],
                [ 5,  2,  4],
                [ 7,  6,  8]])

In [31]:
min(tab)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [32]:
tab.min()

0

In [33]:
np.min(tab)

0

In [34]:
np.min(tab, axis=0)  # Minimum de chaque colonne => Qd résultat est une ligne
#tab.min(axis=0)

array([3, 2, 0])

In [36]:
np.min(tab, axis=1)  #Minimum de chaque ligne => Qd résultat est une colonne

array([0, 3, 3, 2, 6])

In [38]:
np.mean(tab, axis= 1) # Moyenne de chaque ligne

array([5.66666667, 5.66666667, 6.33333333, 3.66666667, 7.        ])

In [39]:
np.sum(tab, axis= 0) # somme de chque colonne

array([34, 33, 18])

In [ ]:
# 5. 