# EXOS ALGORYTHMIQUE TRAINING

In [22]:
import numpy as np
from numpy import random

# 1. Leçons
## 1.1. Leçon 1 : 
> **Identifier le maximum, le minimum des chiffres en parcourant la liste**
### 1. Identification du maximum

In [377]:
# 1 / Identification du maximum

# Exemple 1:

listx = [1,2,3,4,9,6,5]

le_max = -np.inf   # Si on initialise le_max = -l'infini (-np.inf) => Tt chiffre lui sera >
for x in listx: 
    if(x>le_max):
        le_max = x

print(le_max)

9


**Résumé :**
* l'initialisation fixe la varaible le_max à -l'infini
* la 1ière entrée x=1 est comparée à -l'infini --> x=1 > -l'infini => le_max = x=1 
* la 2ième entrée x=2 est comparée à le_max = 1 --> x=2 > 1 => le_max = x=2
* la 3ième entrée x=3 .............. le_max = 2 --> x=3 > 2 => le_max = x=3
* la 4ième entrée x=4 .............. le_max = 3 --> x=4 > 3 => le_max = x=4
* la 5ième entrée x=9 .............. le_max = 4 --> x=9 > 4 => le_max = x=9
* la 6ième entrée x=6 .............. le_max = 9 --> x=6 < 9 => le_max = x=9 RAS
* la 7ième entrée x=5 .............. le_max = 9 --> x=5 < 9 => le_max = x=9 RAS => Output final

In [375]:
# Exemple 2 : 

listx = [1,2,3,4,9,6,5]

le_max = listx[0]        # Ici, le_max est initialisé à listx[0] càd à 1
for x in listx[1:]:      # La boucle commence donc par le 2ième chiffre de la liste = 2
    if(x>le_max):
        le_max = x
    print('Pour x =',x,'dans la liste, après comaraison avec le maximum précédent, le_max reste =',le_max) 

Pour x = 2 dans la liste, après comaraison avec le maximum précédent, le_max reste = 2
Pour x = 3 dans la liste, après comaraison avec le maximum précédent, le_max reste = 3
Pour x = 4 dans la liste, après comaraison avec le maximum précédent, le_max reste = 4
Pour x = 9 dans la liste, après comaraison avec le maximum précédent, le_max reste = 9
Pour x = 6 dans la liste, après comaraison avec le maximum précédent, le_max reste = 9
Pour x = 5 dans la liste, après comaraison avec le maximum précédent, le_max reste = 9


### 2. Identification du minimum

In [387]:
# 2 / Identification du minimum

# Exemple 1:

listx = [8,2,11,7,4,9,6,5]

le_min = +np.inf      # Si on initialise le_min = -np.inf => Impossible car aucun x 
for x in listx:          # ne peut lui inférieur => initialiser à (+)np.inf
    if(x<le_min):     # On décide sur la comparaison <
        le_min = x

print(le_min)

2


In [396]:
# Exemple 2 : 

listx = [1,2,3,4,9,6,5]

le_min = listx[0]        # Ici, le_min est initialisé à listx[0] càd à 1
for x in listx[1:]:      # La boucle commence donc par le 2ième chiffre de la liste = 2
    if(x<le_min):        # On décide sur la comparaison <
        le_min = x
print('Pour x =',x,'dans la liste, après comaraison avec le minimum précédent, le_min reste =',le_min) 

Pour x = 5 dans la liste, après comaraison avec le minimum précédent, le_min reste = 1


## 1.2. Leçon 2 : 
> Différence entre les boucles for & while le principe est le même à une différence, **l'arrêt de la boucle :**
> - La boucle `for` en algorithmique se dit:
>    - **pour l'indice** `allant de début à fin`, **faire** :
> - La boucle `while` se dit:
>    - **tant que** `"condition"` **faire** :

In [542]:
for indice in range(10):
    print(indice)

0
1
2
3
4
5
6
7
8
9


In [543]:
indice = 0 
while indice < 10:
    print(indice)
    indice = indice + 1

0
1
2
3
4
5
6
7
8
9


> **Une autre manière d'utiliser le while est quand tu ne sais pas quand tu dois t'arreter
et d'utiliser un break**

In [13]:
indice = 0 
while True:
    print(indice)
    if indice > 8:
        break
    else:
        indice = indice + 1

0
1
2
3
4
5
6
7
8
9


### Exercice 1
> - **A l'aide de numpy.random.rand(N) créer N nombres aléatoires d'une distribution uniforme**
> - **Faire une fonction (à la main) qui trouve le max et/ou le min de la séquence de valeur (idée parcourir la table et comparer les valeurs 1 à 1 et mettre dans une variable temporaire le maximum**

In [286]:
# 1/Création de N nombres aléatoires d'une distribution uniforme

N = 15
x = random.rand(N)
x

array([0.18594115, 0.81657535, 0.36392274, 0.99421992, 0.72765129,
       0.84370184, 0.76963377, 0.14299959, 0.62352579, 0.052022  ,
       0.48355881, 0.34387978, 0.56473641, 0.82718114, 0.25218572])

In [287]:
x[0+1]

0.8165753450743581

In [289]:
# 2/Création à la main de la fonction qui trouve le maximum

maximum = x.max()
maximum

0.9942199208949689

In [290]:
len(x)

15

In [291]:
range(len(x))

range(0, 15)

In [292]:
# Création de la fonction

listx = x
listx

array([0.18594115, 0.81657535, 0.36392274, 0.99421992, 0.72765129,
       0.84370184, 0.76963377, 0.14299959, 0.62352579, 0.052022  ,
       0.48355881, 0.34387978, 0.56473641, 0.82718114, 0.25218572])

In [295]:
le_max = -np.inf
for x in listx:
    if x>le_max:
        le_max = x
print(le_max)

0.9942199208949689


In [300]:
listx.min()

0.0520220032309886

In [ ]:
# 3/Création à la main de la fonction qui trouve le minimum

In [299]:
le_max = np.inf
for x in listx:
    if x<le_max:
        le_max = x
print(le_max)

0.0520220032309886


In [182]:
# 4 / Autre exemple d'algorithme qui trouve le minimum de L
    # Génération aléatoire d'une suite de chiffres

L = list(random.randint(2, 50, 15))
L

[44, 40, 22, 10, 13, 9, 31, 12, 47, 19, 11, 36, 48, 44, 29]

In [412]:
    # Algorithme qui trouve le minimum de L

L = [44, 40, 22, 10, 13, 9, 31, 12, 47, 19, 11, 36, 48, 44, 29]

le_min = np.inf
for x in L:
    if x<le_min:
        le_min = x

print(le_min)

9


**# Instruction complémentaire :**
> Mettre l'opération qui calcule le minimum d'une liste dans une fonction

In [447]:
# 4 / Créer la fonction automatique correspondante

def func_min(L):
    le_min = L[0]
    for x in L[1:]:
        if(x<le_min):
            le_min = x
    return le_min

In [443]:
L = [1,2,3,4,9,6,5]
func_min(L)

1

In [446]:
func_min([15,4,-6,2,6,-3,10,15])

-6

### Exercice 2
> **Refaire le même exercice avec des échantillons Gaussiens**

In [25]:
# 1/Création de N nombres aléatoires d'une distribution normale (échantillons Gaussiens)

N = 20
x = random.randn(20)
x

array([-1.05516447, -0.15298716, -0.24393665,  0.17974754,  0.2707816 ,
        0.25810667, -0.90775182,  0.01443471, -0.55909242,  0.29378373,
       -0.33649675,  1.45624235,  0.86157077, -1.02762493,  0.4348087 ,
       -0.56401039, -1.81391141,  0.10313723,  0.55998014, -0.08661099])

In [26]:
x.max()

1.4562423502471924

In [27]:
x.min()

-1.8139114138534496

In [28]:
# 2/Création à la main de la fonction qui trouve le maximum

list_gaus = x
list_gaus

array([-1.05516447, -0.15298716, -0.24393665,  0.17974754,  0.2707816 ,
        0.25810667, -0.90775182,  0.01443471, -0.55909242,  0.29378373,
       -0.33649675,  1.45624235,  0.86157077, -1.02762493,  0.4348087 ,
       -0.56401039, -1.81391141,  0.10313723,  0.55998014, -0.08661099])

In [29]:
le_max = -np.inf
for x in list_gaus: 
    if(x>le_max):
        le_max = x

print(le_max)

1.4562423502471924


In [30]:
# 3/Création à la main de la fonction qui trouve le minimum

le_min = list_gaus[0]
for x in list_gaus[1:]:
    if x<le_min:
        le_min = x
print(le_min)

-1.8139114138534496


In [31]:
# Créer la fonction automatique correspondant

def fonct_max(L):
    le_max = -np.inf
    for x in L: 
        if(x>le_max):
            le_max = x
    return le_max

In [33]:
L = list_gaus
fonct_max(L)

1.4562423502471924

### Exercice 3
> **Dans une boucle for, écrire un algorithme permettant de vider une liste pour en remplir une autre**

=> Partir d'une liste de valeur et dans une boucle remplir une nouvelle liste avec les valeurs de la liste données en entrée et supprimer de la liste d'entrée la valeur qui vient d'y être être copiée

In [ ]:
Exemples: 
    
liste entrée : [1 , 2 , 3 , 4] 
liste sortie : [] 

iteration 1 : 
liste entrée : [2 , 3 , 4] 
liste sortie : [1]

iteration 2
liste entrée : [ 3 , 4] 
liste sortie : [1,2]

iteration 3
liste entrée : [4] 
liste sortie : [1,2,3] 

iteration 4 
liste entrée : [] 
liste sortie : [1,2,3,4]

In [427]:
# EXEMPLE 1 :

liste_entree = [1,2,3,4]
liste_sortie = []

for x in liste_entree[:]:
    liste_entree.remove(x)
    print('---------------')
    print(liste_entree)
    liste_sortie.append(x)
    print(liste_sortie)

---------------
[2, 3, 4]
[1]
---------------
[3, 4]
[1, 2]
---------------
[4]
[1, 2, 3]
---------------
[]
[1, 2, 3, 4]


In [430]:
# EXEMPLE 2 :

liste_entree = [1,2,3,4,9,6,5,8,10]
liste_sortie = []

for x in liste_entree[:]:
    liste_entree.remove(x)
    print('-------------------------------')
    print(liste_entree)
    liste_sortie.append(x)
    print(liste_sortie)

-------------------------------
[2, 3, 4, 9, 6, 5, 8, 10]
[1]
-------------------------------
[3, 4, 9, 6, 5, 8, 10]
[1, 2]
-------------------------------
[4, 9, 6, 5, 8, 10]
[1, 2, 3]
-------------------------------
[9, 6, 5, 8, 10]
[1, 2, 3, 4]
-------------------------------
[6, 5, 8, 10]
[1, 2, 3, 4, 9]
-------------------------------
[5, 8, 10]
[1, 2, 3, 4, 9, 6]
-------------------------------
[8, 10]
[1, 2, 3, 4, 9, 6, 5]
-------------------------------
[10]
[1, 2, 3, 4, 9, 6, 5, 8]
-------------------------------
[]
[1, 2, 3, 4, 9, 6, 5, 8, 10]


### Exercice 4
> **Créer une opération qui permet de trier une liste du plus petit au plus grand** (en se basant sur le principe de remplissage/réduction de liste de l'exo précédent)

In [1]:
liste_test = [1,2,3,4,9,6,5,8,10]
liste_sortie = []

for x in liste_test[:]:
    liste_test.remove(x)
    print('-------------------------------')
    print(liste_test)
    liste_sortie.append(x)
    print(liste_sortie)

-------------------------------
[2, 3, 4, 9, 6, 5, 8, 10]
[1]
-------------------------------
[3, 4, 9, 6, 5, 8, 10]
[1, 2]
-------------------------------
[4, 9, 6, 5, 8, 10]
[1, 2, 3]
-------------------------------
[9, 6, 5, 8, 10]
[1, 2, 3, 4]
-------------------------------
[6, 5, 8, 10]
[1, 2, 3, 4, 9]
-------------------------------
[5, 8, 10]
[1, 2, 3, 4, 9, 6]
-------------------------------
[8, 10]
[1, 2, 3, 4, 9, 6, 5]
-------------------------------
[10]
[1, 2, 3, 4, 9, 6, 5, 8]
-------------------------------
[]
[1, 2, 3, 4, 9, 6, 5, 8, 10]


### Exercice 5
> **Maintenant, combiner l'opération de recherche de min et la reduction de liste pour créer une fonction de trie (=> Création de sa propre fonction 'sort')**

In [92]:
def func_min(L):
    le_min = L[0]
    for x in L[1:]:
        if(x<le_min):
            le_min = x
    return le_min

def func_trier(L):
    liste_ordonnee = []
    while L:
        le_min = func_min(L)
        if le_min == func_min(L):
            L.remove(le_min)
            liste_ordonnee.append(le_min)
    return liste_ordonnee

In [95]:
L = [7,1,2,3,0,4,9,6,5,8,10]

func_trier(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [36]:
# Alternative, Non conseillée

liste_test = []
liste_sortie = []

def func_trier(liste_test):
    liste_sortie = []
    while liste_test:
        le_min = liste_test[0]
        for x in liste_test:
            if x<le_min:
                le_min = x
        liste_test.remove(le_min )
        liste_sortie.append(le_min )

    return liste_sortie

In [37]:
liste_test = [1,2,3,4,0,9,6,-4,5,8,10]
func_trier(liste_test)

[-4, 0, 1, 2, 3, 4, 5, 6, 8, 9, 10]

### Exercice 6
> **A l'aide de boucle for, calculer quelques série mathématiques connu et comparer le résultat à la théorie Sum 1/n^2 , Sum n etc...**