# EXOS ALGORYTHMIQUE TRAINING

In [283]:
import numpy as np
from numpy import random

### Leçon 1 : 
> **Identifier le maximum, le minimum des chiffres en parcourant la liste**

In [377]:
# 1 / Identification du maximum

# Exemple 1:

listx = [1,2,3,4,9,6,5]

le_max = -np.inf   # Si on initialise le_max = -l'infini (-np.inf) => Tt chiffre lui sera >
for x in listx: 
    if(x>le_max):
        le_max = x

print(le_max)

9


**Résumé :**
* l'initialisation fixe la varaible le_max à -l'infini
* la 1ière entrée x=1 est comparée à -l'infini --> x=1 > -l'infini => le_max = x=1 
* la 2ième entrée x=2 est comparée à le_max = 1 --> x=2 > 1 => le_max = x=2
* la 3ième entrée x=3 .............. le_max = 2 --> x=3 > 2 => le_max = x=3
* la 4ième entrée x=4 .............. le_max = 3 --> x=4 > 3 => le_max = x=4
* la 5ième entrée x=9 .............. le_max = 4 --> x=9 > 4 => le_max = x=9
* la 6ième entrée x=6 .............. le_max = 9 --> x=6 < 9 => le_max = x=9 RAS
* la 7ième entrée x=5 .............. le_max = 9 --> x=5 < 9 => le_max = x=9 RAS => Output final

In [375]:
# Exemple 2 : 

listx = [1,2,3,4,9,6,5]

le_max = listx[0]        # Ici, le_max est initialisé à listx[0] càd à 1
for x in listx[1:]:      # La boucle commence donc par le 2ième chiffre de la liste = 2
    if(x>le_max):
        le_max = x
    print('Pour x =',x,'dans la liste, après comaraison avec le maximum précédent, le_max reste =',le_max) 

Pour x = 2 dans la liste, après comaraison avec le maximum précédent, le_max reste = 2
Pour x = 3 dans la liste, après comaraison avec le maximum précédent, le_max reste = 3
Pour x = 4 dans la liste, après comaraison avec le maximum précédent, le_max reste = 4
Pour x = 9 dans la liste, après comaraison avec le maximum précédent, le_max reste = 9
Pour x = 6 dans la liste, après comaraison avec le maximum précédent, le_max reste = 9
Pour x = 5 dans la liste, après comaraison avec le maximum précédent, le_max reste = 9


In [387]:
# 2 / Identification du minimum

# Exemple 1:

listx = [8,2,11,7,4,9,6,5]

le_min = +np.inf      # Si on initialise le_min = -np.inf => Impossible car aucun x 
for x in listx:          # ne peut lui inférieur => initialiser à (+)np.inf
    if(x<le_min):     # On décide sur la comparaison <
        le_min = x

print(le_min)

2


In [396]:
# Exemple 2 : 

listx = [1,2,3,4,9,6,5]

le_min = listx[0]        # Ici, le_min est initialisé à listx[0] càd à 1
for x in listx[1:]:      # La boucle commence donc par le 2ième chiffre de la liste = 2
    if(x<le_min):        # On décide sur la comparaison <
        le_min = x
print('Pour x =',x,'dans la liste, après comaraison avec le minimum précédent, le_min reste =',le_min) 

Pour x = 5 dans la liste, après comaraison avec le minimum précédent, le_min reste = 1


## Exercice 1
> - **A l'aide de numpy.random.rand(N) créer N nombres aléatoires d'une distribution uniforme**
> - **Faire une fonction (à la main) qui trouve le max et/ou le min de la séquence de valeur (idée parcourir la table et comparer les valeurs 1 à 1 et mettre dans une variable temporaire le maximum**

In [286]:
# 1/Création de N nombres aléatoires d'une distribution uniforme

N = 15
x = random.rand(N)
x

array([0.18594115, 0.81657535, 0.36392274, 0.99421992, 0.72765129,
       0.84370184, 0.76963377, 0.14299959, 0.62352579, 0.052022  ,
       0.48355881, 0.34387978, 0.56473641, 0.82718114, 0.25218572])

In [287]:
x[0+1]

0.8165753450743581

In [289]:
# 2/Création à la main de la fonction qui trouve le maximum

maximum = x.max()
maximum

0.9942199208949689

In [290]:
len(x)

15

In [291]:
range(len(x))

range(0, 15)

In [292]:
# Création de la fonction

listx = x
listx

array([0.18594115, 0.81657535, 0.36392274, 0.99421992, 0.72765129,
       0.84370184, 0.76963377, 0.14299959, 0.62352579, 0.052022  ,
       0.48355881, 0.34387978, 0.56473641, 0.82718114, 0.25218572])

In [295]:
le_max = -np.inf
for x in listx:
    if x>le_max:
        le_max = x
print(le_max)

0.9942199208949689


In [300]:
listx.min()

0.0520220032309886

In [ ]:
# 3/Création à la main de la fonction qui trouve le minimum

In [299]:
le_max = np.inf
for x in listx:
    if x<le_max:
        le_max = x
print(le_max)

0.0520220032309886


In [154]:
# 4 / Créer la fonction automatique correspondante (A revoir !)

def fonct_max():
    for i in num_list:
        maximum = max(num_list)
        return maximum

## Exercice 2
> **Refaire le même exercice avec des échantillons Gaussiens**

In [405]:
# 1/Création de N nombres aléatoires d'une distribution normale (échantillons Gaussiens)

N = 20
x = random.randn(20)
x

array([-0.28888912,  0.15182056,  1.03771425,  1.09183213,  0.47590942,
        1.4446756 ,  1.07628393,  1.12504325, -0.18836423, -1.22439149,
        0.6846631 ,  0.66256948, -0.55139452, -0.10362017, -1.32214391,
       -0.45864127, -1.33513046, -0.00347976, -0.12703654, -1.51994195])

In [406]:
x.max()

1.4446756014944773

In [407]:
x.min()

-1.5199419460170627

In [408]:
# 2/Création à la main de la fonction qui trouve le maximum

list_gaus = x
list_gaus

array([-0.28888912,  0.15182056,  1.03771425,  1.09183213,  0.47590942,
        1.4446756 ,  1.07628393,  1.12504325, -0.18836423, -1.22439149,
        0.6846631 ,  0.66256948, -0.55139452, -0.10362017, -1.32214391,
       -0.45864127, -1.33513046, -0.00347976, -0.12703654, -1.51994195])

In [409]:
le_max = -np.inf
for x in list_gaus: 
    if(x>le_max):
        le_max = x

print(le_max)

1.4446756014944773


In [411]:
# 3/Création à la main de la fonction qui trouve le minimum

le_min = list_gaus[0]
for x in list_gaus[1:]:
    if x<le_min:
        le_min = x
print(le_min)

-1.5199419460170627


In [58]:
# Créer la fonction automatique correspondant (A revoir)

def fonct_min():
    for i in num_list:
        minimum = min(num_list)
        return minimum

## Exercice 3
> **Réussir à classer une séquence en ordre croissant puis décroissant**

In [41]:
# 1/Convertir num_list en Dataframe

import pandas as pd

num_list_df = pd.DataFrame(num_list)
num_list_df

0
0  -2.078626
1  -1.887167
2  -0.968863
3  -0.778103
4  -0.766557
5  -0.687142
6  -0.630369
7  -0.295480
8  -0.143564
9  -0.020449
10  0.028052
11  0.082172
12  0.124827
13  0.187131
14  0.269651
15  0.302945
16  0.764593
17  0.907851
18  1.276809
19  1.671880

In [50]:
# Classement par ordre croissant 

num_list_df.sort_values([0], ascending = True)

0
0  -2.078626
1  -1.887167
2  -0.968863
3  -0.778103
4  -0.766557
5  -0.687142
6  -0.630369
7  -0.295480
8  -0.143564
9  -0.020449
10  0.028052
11  0.082172
12  0.124827
13  0.187131
14  0.269651
15  0.302945
16  0.764593
17  0.907851
18  1.276809
19  1.671880

In [51]:
# Classement par orde décroissant

num_list_df.sort_values([0], ascending = False)

0
19  1.671880
18  1.276809
17  0.907851
16  0.764593
15  0.302945
14  0.269651
13  0.187131
12  0.124827
11  0.082172
10  0.028052
9  -0.020449
8  -0.143564
7  -0.295480
6  -0.630369
5  -0.687142
4  -0.766557
3  -0.778103
2  -0.968863
1  -1.887167
0  -2.078626

## Exercice 4
> **A l'aide de boucle for, calculer quelques série mathématiques connu et comparer le résultat à la théorie Sum 1/n^2 , Sum n etc...**

In [182]:
# 1/Génération aléatoire d'une suite de chiffres

L = list(random.randint(2, 50, 15))
L

[44, 40, 22, 10, 13, 9, 31, 12, 47, 19, 11, 36, 48, 44, 29]

In [412]:
# Algorithme qui trouve le minimum de L

L = [44, 40, 22, 10, 13, 9, 31, 12, 47, 19, 11, 36, 48, 44, 29]

le_min = np.inf
for x in L:
    if x<le_min:
        le_min = x

print(le_min)

9


**Enoncé**
> - Il faut que tu partes encore une fois d'une liste de valeur et 
> - que dans une boucle tu remplisses une nouvelle liste avec les valeurs de la liste données en entré et que 
> - tu supprimes de la liste d'entrée la valeur que tu viens de copier.

In [ ]:
Exemples: 
    
liste entrée : [1 , 2 , 3 , 4] 
liste sortie : [] 

iteration 1 : 
liste entrée : [2 , 3 , 4] 
liste sortie : [1]

iteration 2
liste entrée : [ 3 , 4] 
liste sortie : [1,2]

iteration 3
liste entrée : [4] 
liste sortie : [1,2,3] 

iteration 4 
liste entrée : [] 
liste sortie : [1,2,3,4]

In [427]:
liste_entree = [1,2,3,4]
liste_sortie = []

for x in liste_entree[:]:
    liste_entree.remove(x)
    print('---------------')
    print(liste_entree)
    liste_sortie.append(x)
    print(liste_sortie)

---------------
[2, 3, 4]
[1]
---------------
[3, 4]
[1, 2]
---------------
[4]
[1, 2, 3]
---------------
[]
[1, 2, 3, 4]


In [430]:
liste_entree = [1,2,3,4,9,6,5,8,10]
liste_sortie = []

for x in liste_entree[:]:
    liste_entree.remove(x)
    print('-------------------------------')
    print(liste_entree)
    liste_sortie.append(x)
    print(liste_sortie)

-------------------------------
[2, 3, 4, 9, 6, 5, 8, 10]
[1]
-------------------------------
[3, 4, 9, 6, 5, 8, 10]
[1, 2]
-------------------------------
[4, 9, 6, 5, 8, 10]
[1, 2, 3]
-------------------------------
[9, 6, 5, 8, 10]
[1, 2, 3, 4]
-------------------------------
[6, 5, 8, 10]
[1, 2, 3, 4, 9]
-------------------------------
[5, 8, 10]
[1, 2, 3, 4, 9, 6]
-------------------------------
[8, 10]
[1, 2, 3, 4, 9, 6, 5]
-------------------------------
[10]
[1, 2, 3, 4, 9, 6, 5, 8]
-------------------------------
[]
[1, 2, 3, 4, 9, 6, 5, 8, 10]
