# EXOS ALGORYTHMIQUE TRAINING

## Exercice 1
> - **A l'aide de numpy.random.rand(N) créer N nombres aléatoires d'une distribution uniforme**
> - **Faire une fonction (à la main) qui trouve le max et/ou le min de la séquence de valeur (idée parcourir la table et comparer les valeurs 1 à 1 et mettre dans une variable temporaire le maximum**

In [177]:
import numpy as np
from numpy import random

In [143]:
# 1/Création de N nombres aléatoires d'une distribution uniforme

N = 15
x = random.rand(N)
x

array([0.51318155, 0.82408456, 0.54950946, 0.755878  , 0.1754822 ,
       0.2013702 , 0.19938686, 0.9323083 , 0.02716207, 0.52548766,
       0.67829365, 0.39921442, 0.79003026, 0.28459122, 0.19516889])

In [144]:
x[0+1]

0.8240845648741437

In [145]:
# 2/Création à la main de la fonction qui trouve le maximum

maximum = x.max()
maximum

0.9323082976728178

In [146]:
len(x)

15

In [147]:
range(len(x))

range(0, 15)

In [148]:
# Création de la fonction

for i in range(len(x)-1):
    if x[i] > x[i+1]:
        maximum = x[i]  
    else:
        maximum = x[i+1]
print(maximum)

0.284591223890558


In [149]:
listx = x
listx

array([0.51318155, 0.82408456, 0.54950946, 0.755878  , 0.1754822 ,
       0.2013702 , 0.19938686, 0.9323083 , 0.02716207, 0.52548766,
       0.67829365, 0.39921442, 0.79003026, 0.28459122, 0.19516889])

In [150]:
le_max = -np.inf
le_max

-inf

In [151]:
for x in listx:
    if x>le_max:
        le_max = x
print(le_max)

0.9323082976728178


In [222]:
listx = [1,2,3,4,9,6,5]

le_max = -np.inf 
for x in listx: 
    if(x>le_max):
        le_max = x

print(le_max)

9


In [154]:
# Créer la fonction automatique correspondante (A revoir !)

def fonct_max():
    for i in num_list:
        maximum = max(num_list)
        return maximum

## Exercice 2
> **Refaire le même exercice avec des échantillons Gaussiens**

In [53]:
# 1/Création de N nombres aléatoires d'une distribution normale (échantillons Gaussiens)

N = 20
x = random.randn(20)
x

array([-0.19474103,  1.53110801, -0.94810106,  0.16249851, -0.34143489,
        0.65390907,  1.02657916,  0.45989092, -0.82289171,  1.07521008,
        0.48231005, -1.10129002, -1.77291341,  1.71349266, -0.49437202,
       -2.41727262, -1.36073399, -0.67692209, -0.11441419,  0.61309932])

In [66]:
x.min()

-2.417272624003228

In [86]:
range(len(x))

range(0, 20)

In [84]:
# 2/Création à la main de la fonction qui trouve le maximum

for i in range(len(x)-1):
    if x[i] > x[i+1]:
        minimum = x[i+1]
    else:
        minimum = x[i]
print(minimum)

-0.11441419363408285


In [58]:
# Créer la fonction automatique correspondant (A revoir)

def fonct_min():
    for i in num_list:
        minimum = min(num_list)
        return minimum

## Exercice 3
> **Réussir à classer une séquence en ordre croissant puis décroissant**

In [41]:
# 1/Convertir num_list en Dataframe

import pandas as pd

num_list_df = pd.DataFrame(num_list)
num_list_df

0
0  -2.078626
1  -1.887167
2  -0.968863
3  -0.778103
4  -0.766557
5  -0.687142
6  -0.630369
7  -0.295480
8  -0.143564
9  -0.020449
10  0.028052
11  0.082172
12  0.124827
13  0.187131
14  0.269651
15  0.302945
16  0.764593
17  0.907851
18  1.276809
19  1.671880

In [50]:
# Classement par ordre croissant 

num_list_df.sort_values([0], ascending = True)

0
0  -2.078626
1  -1.887167
2  -0.968863
3  -0.778103
4  -0.766557
5  -0.687142
6  -0.630369
7  -0.295480
8  -0.143564
9  -0.020449
10  0.028052
11  0.082172
12  0.124827
13  0.187131
14  0.269651
15  0.302945
16  0.764593
17  0.907851
18  1.276809
19  1.671880

In [51]:
# Classement par orde décroissant

num_list_df.sort_values([0], ascending = False)

0
19  1.671880
18  1.276809
17  0.907851
16  0.764593
15  0.302945
14  0.269651
13  0.187131
12  0.124827
11  0.082172
10  0.028052
9  -0.020449
8  -0.143564
7  -0.295480
6  -0.630369
5  -0.687142
4  -0.766557
3  -0.778103
2  -0.968863
1  -1.887167
0  -2.078626

## Exercice 4
> **A l'aide de boucle for, calculer quelques série mathématiques connu et comparer le résultat à la théorie Sum 1/n^2 , Sum n etc...**

In [182]:
# 1/Génération aléatoire d'une suite de chiffres

L = list(random.randint(2, 50, 15))
L

[44, 40, 22, 10, 13, 9, 31, 12, 47, 19, 11, 36, 48, 44, 29]

In [220]:
# Algorithme qui trouve le minimum de L

L = [44, 40, 22, 10, 13, 9, 31, 12, 47, 19, 11, 36, 48, 44, 29]

le_min = np.inf
for x in L:
    if le_min > x:
        le_min = x

print(le_min)

9
